[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-predict"
version = "1.0.0"
description = "AI Prediction API for Bank Sampah OSKU"
requires-python = ">=3.9"
